import os
import re
import glob
import filecmp
import hashlib
import autoc


_caption = f"/* Automagically generated by autoc {autoc.__version__} */"


class _EntityContainer:
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)
    self.entities = set()

  def add(self, entity):
    self.entities.add(entity)
    return self


class _Builder(list):
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)
    self.complexity = 0

  def append(self, obj):
    s = str(obj)
    self.complexity += len(s)
    super().append(s)


class _SmartRenderer:
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)

  @property
  def digest(self):
    return self.__digest
  
  def render(self):
    stream = self.stream
    path = stream.path
    try:
      self.render_contents(stream)
      self.__digest = stream.digest
    finally:
      stream.close()
    if not os.path.exists(self.file_name):
      os.replace(path, self.file_name)
    elif self.module.stateful:
      if self.module.digests.get(self.file_name) != self.__digest:
        os.replace(path, self.file_name)
      else:
        os.unlink(path)
    else:
      if not filecmp.cmp(path, self.file_name, shallow=False):
        os.replace(path, self.file_name)
      else:
        os.unlink(path)


def _sort_entities(entities):
  return sorted(entities, key=lambda e: e._order_key)


#
class Header(_EntityContainer, _SmartRenderer):
  
  __stream = None
  
  def __init__(self, module, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module
    self.file_name = f"{self.module.name}_auto.h"

  @property
  def tag(self):
    clean = re.sub(r'[^A-Za-z0-9_]', '_', self.module.name)
    return f"{clean}_auto_h".upper()

  @property
  def stream(self):
    if self.__stream is None:
      self.__stream = _StreamFile(self.file_name + "~")
    return self.__stream

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #ifndef {self.tag}
      #define {self.tag}
    """.lstrip())

  def render_contents(self, stream):
    self.render_prologue(stream)
    entities = _sort_entities(self.entities)
    for e in entities:
      for chunk in e._header_declarations:
        stream.write(chunk)
    for e in entities:
      for chunk in e._header_definitions:
        stream.write(chunk)
    self.render_epilogue(stream)

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #ifndef {self.tag}
      #define {self.tag}
    """.lstrip())

  def render_epilogue(self, stream):
    stream.write("\n#endif\n")


#
class Source(_EntityContainer, _SmartRenderer):
  
  complexity = 0
  __stream = None

  def __init__(self, module, index, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module
    self.index = index
    self.file_name = self._generate_file_name(self.module.name, self.index, self.module.source_count)

  @classmethod
  def _generate_file_name(self, prefix, index, count):
    return f"{prefix}_auto{index}.c" if count > 1 else f"{prefix}_auto.c"

  @property
  def stream(self):
    if self.__stream is None:
      self.__stream = _StreamFile(self.file_name + "~")
    return self.__stream

  def add(self, entity):
    if entity not in self.entities:
      self.complexity += entity.complexity
    self.entities.add(entity)
    return self

  def render_contents(self, stream):
    self.render_prologue(stream)
    total_entities = set()
    for e in self.entities:
      total_entities.update(e.total_references)
    for e in _sort_entities(total_entities):
      for chunk in e._source_declarations:
        stream.write(chunk)
    for e in _sort_entities(self.entities):
      for chunk in e._source_definitions:
        stream.write(chunk)

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #include "{self.module.header.file_name}"
    """.lstrip())


_build_context = None


#
class Module:

  __entities = None
  __header = None
  __sources = None
  __digests = None
  __total_entities = None

  def __init__(self, name, *args, stateful=True, source_count=None, source_threshold=None, source=Source, header=Header, **kws):
    super().__init__(*args, **kws)
    self.name = str(name)
    self.stateful = stateful
    self.source_count = source_count
    self.source_threshold = source_threshold
    self.__header_ctor = header
    self.__source_ctor = source

  @property
  def entities(self):
    if self.__entities is None:
      self.__entities = set()
    return self.__entities

  def add(self, entity):
    self.entities.add(entity)
    return self

  @property
  def header(self):
    if self.__header is None:
      self.__header = self.__header_ctor(self)
    return self.__header

  @property
  def sources(self):
    if self.__sources is None:
      if self.source_count is None:
        raise ValueError("source_count must be set before accessing sources")
      self.__sources = [self.__source_ctor(self, i) for i in range(1, self.source_count + 1)]
    return self.__sources

  @property
  def digests(self):
    if self.__digests is None:
      self.__digests = _State(self).read()
    return self.__digests

  def __cleanup_sources(self):
    produced = {s.file_name for s in self.sources}
    # FIXME more robust approach to detect the sources location based on the file name generation scheme
    rxs = tuple(re.compile(f"^{self.__source_ctor._generate_file_name(re.escape(self.name), i, c)}$") for i, c in ((None, 0), (r"\d+", 2)))
    for f in glob.glob(self.__source_ctor._generate_file_name(self.name, "*", 2)):
      if f not in produced and any(rx.match(f) for rx in rxs):
        try:
          os.unlink(f)
        except OSError:
          pass
    return self

  def render(self):
    self.distribute_entities()
    self.__cleanup_sources()
    self.header.render()
    for source in self.sources:
      source.render()
    if self.stateful:
      _State(self).collect().write()
    else:
      state = _State(self)
      if os.path.exists(state.file_name):
        try:
          os.unlink(state.file_name)
        except OSError:
          pass
    return self

  @property
  def total_entities(self):
    if self.__total_entities is None:
      entities = set()
      for e in self.entities:
        entities.update(e.total_references)
      self.__total_entities = entities
    return self.__total_entities

  def distribute_entities(self):
    self.header.entities.update(self.total_entities)
    if self.source_count is None:
      if self.source_threshold is None:
        self.source_count = 1
      else:
        total_complexity = sum(e.complexity for e in self.total_entities)
        self.source_count = int((total_complexity / self.source_threshold) + 0.999)  # ceil
    # Allow to disable sources rendering by setting source_count to 0
    if self.source_count > 0:
      for e in _sort_entities(self.total_entities):
        self.sources.sort(key=lambda s: s.complexity)
        self.sources[0].add(e)

  def __enter__(self):
    return self

  def __exit__(self, exc_type, exc_value, traceback):
    self.render()
    if _build_context:
      _build_context.module = self
    return False


class _State(dict):
  def __init__(self, module, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module

  @property
  def file_name(self):
    dirname, basename = os.path.split(self.module.name)
    state_dir = os.path.join(dirname, ".autoc") if dirname else ".autoc"
    return os.path.join(state_dir, f"{basename}.state")

  def collect(self):
    self[self.module.header.file_name] = self.module.header.digest
    for source in self.module.sources:
      self[source.file_name] = source.digest
    return self

  def read(self):
    if os.path.exists(self.file_name):
      if self.module.stateful:
        with open(self.file_name, "rt") as io:
          for line in io:
            line = line.strip()
            if not line:
              continue
            match = re.match(r"\s*([^\s]+)\s+\*(.*)", line)
            if match is None:
              raise ValueError("bad state file format")
            digest, fname = match.groups()
            self[fname] = digest
      else:
        try:
          os.unlink(self.file_name)
        except OSError:
          pass
    return self

  def write(self):
    dirname = os.path.dirname(self.file_name)
    if dirname:
      os.makedirs(dirname, exist_ok=True)
    with open(self.file_name, "wt") as io:
      for file_name, digest in sorted(self.items()):
        io.write(f"{digest} *{file_name}\n")
    return self


class _StreamFile:
  def __init__(self, path, mode="wt", *args, **kws):
    super().__init__(*args, **kws)
    self.__file = open(path, mode)
    self.__digest = hashlib.md5()
    self.path = path

  @property
  def digest(self):
    return self.__digest.hexdigest()

  def write(self, data):
    self.__file.write(data)
    self.__digest.update(data.encode("utf-8"))

  def close(self): self.__file.close()

  def __enter__(self): return self

  def __exit__(self, exc_type, exc_val, exc_tb): self.close()


#
class Entity:
  
  __hdefs = None
  __sdefs = None
  __hdecls = None
  __sdecls = None
  __position = None
  __total_references = None
  __total_dependencies = None
  __order_key = None
  
  def __init__(self, *args, dependencies=(), references=(), **kws):
    super().__init__(*args, **kws)
    self.references = set()
    self.references.update(references)
    self.dependencies = _DependencySet(self)
    self.dependencies.update(dependencies)

  @property
  def _order_key(self):
    # Total order over entities: topological position first, then the rendered
    # contents - this keeps the generation deterministic across the processes
    # by eliminating the set iteration order from the output
    if self.__order_key is None:
      self.__order_key = (
        self.position,
        str().join(self._header_declarations),
        str().join(self._source_declarations),
        str().join(self._source_definitions)
      )
    return self.__order_key

  def __lt__(self, other):
    return self._order_key < other._order_key

  @property
  def total_references(self):
    if self.__total_references is None:
      self.__total_references = self.collect_references(set())
    return self.__total_references

  @property
  def total_dependencies(self):
    if self.__total_dependencies is None:
      self.__total_dependencies = self.collect_dependencies(set())
    return self.__total_dependencies

  def collect_references(self, entities):
    if self not in entities:
      entities.add(self)
      if self.__total_references is not None:
        entities.update(self.__total_references)
      else:
        for ref in self.references:
          ref.collect_references(entities)
    return entities

  def collect_dependencies(self, entities):
    if self not in entities:
      entities.add(self)
      if self.__total_dependencies is not None:
        entities.update(self.__total_dependencies)
      else:
        for dep in self.dependencies:
          dep.collect_dependencies(entities)
    return entities

  @property
  def position(self):
    if self.__position is None:
      p = 0
      for d in self.total_dependencies:
        if d is not self:
          p = max(p, d.position)
      self.__position = p + 1
    return self.__position

  @property
  def complexity(self):
    return self._source_declarations.complexity + self._source_definitions.complexity

  def render_declarations(self, stream, header): pass
  
  def render_definitions(self, stream, header): pass

  @property
  def _header_declarations(self):
    if self.__hdecls is None:
      self.__hdecls = _Builder()
      self.render_declarations(self.__hdecls, True)
    return self.__hdecls

  @property
  def _header_definitions(self):
    if self.__hdefs is None:
      self.__hdefs = _Builder()
      self.render_definitions(self.__hdefs, True)
    return self.__hdefs
      
  @property
  def _source_declarations(self):
    if self.__sdecls is None:
      self.__sdecls = _Builder()
      self.render_declarations(self.__sdecls, False)
    return self.__sdecls

  @property
  def _source_definitions(self):
    if self.__sdefs is None:
      self.__sdefs = _Builder()
      self.render_definitions(self.__sdefs, False)
    return self.__sdefs


class _DependencySet(set):
  def __init__(self, entity, *args, **kws):
    super().__init__(*args, **kws)
    self.entity = entity

  def add(self, entity):
    self.entity.references.add(entity)
    super().add(entity)
    
  def update(self, *entities):
    self.entity.references.update(*entities)
    super().update(*entities)

#
class Code(Entity):
  def __init__(self, *args, interface=None, implementation=None, definitions=None, **kws):
    super().__init__(*args, **kws)
    self.__interface = interface
    self.__definitions = definitions
    self.__implementation = implementation

  def __repr__(self):
    return f"... <{self.__class__.__name__}>"

  def render_declarations(self, stream, header):
    if header:
      if self.__interface:
        stream.append(self.__interface)
    else:
      if self.__definitions:
        stream.append(self.__definitions)

  def render_definitions(self, stream, header):
    if not header:
      if self.__implementation:
        stream.append(self.__implementation)


#
class SystemHeader(Code):
  def __init__(self, header, *args, **kws):
    self.header_name = header
    super().__init__(interface=f"#include <{header}>\n", *args, **kws)

  def __repr__(self):
    return f"{self.header_name} <{self.__class__.__name__}>"