import os
import re
import hashlib
import autoc


_caption = f"/* Automagically generated by autoc {autoc.__version__} */"


class _EntityContainer:
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)
    self.entities = set()

  def add(self, entity):
    self.entities.add(entity)
    return self


class _Builder(list):
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)
    self.complexity = 0

  def append(self, obj):
    s = str(obj)
    self.complexity += len(s)
    super().append(s)


#
class Module:

  source_count = 1
  source_threshold = None
  __entities = None
  __header = None
  __sources = None
  __digests = None
  __total_entities = None

  def __init__(self, name, stateful=True, *args, **kws):
    super().__init__(*args, **kws)
    self.name = str(name)
    self.stateful = stateful

  @property
  def entities(self):
    if self.__entities is None:
      self.__entities = set()
    return self.__entities

  def add(self, entity):
    self.entities.add(entity)
    return self

  @property
  def header(self):
    if self.__header is None:
      self.__header = Header(self)
    return self.__header

  @property
  def sources(self):
    if self.__sources is None:
      if self.source_count is None:
        raise ValueError("source_count must be set before accessing sources")
      self.__sources = [Source(self, i) for i in range(1, self.source_count + 1)]
    return self.__sources

  @property
  def digests(self):
    if self.__digests is None:
      self.__digests = _State(self).read()
    return self.__digests

  def render(self):
    self.distribute_entities()
    self.header.render()
    for source in self.sources:
      source.render()
    if self.stateful:
      _State(self).collect().write()
    return self

  @property
  def total_entities(self):
    if self.__total_entities is None:
      entities = set()
      for e in self.entities:
        entities.update(e.total_references)
      self.__total_entities = entities
    return self.__total_entities

  def distribute_entities(self):
    self.header.entities.update(self.total_entities)
    if self.source_count is None:
      if self.source_threshold is None:
        self.source_count = 1
      else:
        total_complexity = sum(e.complexity for e in self.total_entities)
        self.source_count = int((total_complexity / self.source_threshold) + 0.999)  # ceil
    for e in self.total_entities:
      self.sources.sort(key=lambda s: s.complexity)
      self.sources[0].add(e)

  def __enter__(self):
    return self

  def __exit__(self, exc_type, exc_value, traceback):
    self.render()
    return False


class _State(dict):
  def __init__(self, module, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module

  @property
  def file_name(self): return f"{self.module.name}.state"

  def collect(self):
    self[self.module.header.file_name] = self.module.header.digest
    for source in self.module.sources:
      self[source.file_name] = source.digest
    return self

  def read(self):
    if os.path.exists(self.file_name):
      if self.module.stateful:
        with open(self.file_name, "rt") as io:
          for line in io:
            line = line.strip()
            if not line:
              continue
            match = re.match(r"\s*([^\s]+)\s+\*(.*)", line)
            if match is None:
              raise ValueError("bad state file format")
            digest, fname = match.groups()
            self[fname] = digest
      else:
        # Delete stray state file on (porbable) switch from stateful operation to stateless
        os.unlink(self.file_name)
    return self

  def write(self):
    with open(self.file_name, "wt") as io:
      for file_name, digest in sorted(self.items()):
        io.write(f"{digest} *{file_name}\n")
    return self


class _StreamFile:
  def __init__(self, path, mode="wt", *args, **kws):
    super().__init__(*args, **kws)
    self.__file = open(path, mode)
    self.__digest = hashlib.md5()
    self.path = path

  @property
  def digest(self):
    return self.__digest.hexdigest()

  def write(self, data):
    self.__file.write(data)
    self.__digest.update(data.encode("utf-8"))

  def close(self): self.__file.close()

  def __enter__(self): return self

  def __exit__(self, exc_type, exc_val, exc_tb): self.close()


class _SmartRenderer:
  def __init__(self, *args, **kws):
    super().__init__(*args, **kws)

  @property
  def digest(self):
    return self.__digest
  
  def render(self):
    stream = self.stream
    path = stream.path
    try:
      self.render_contents(stream)
      self.__digest = stream.digest
    finally:
      stream.close()
    if not os.path.exists(self.file_name) or self.module.digests.get(self.file_name) != self.__digest:
      os.replace(path, self.file_name)
    else:
      os.unlink(path)


#
class Header(_EntityContainer, _SmartRenderer):
  
  __stream = None
  
  def __init__(self, module, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module

  @property
  def file_name(self):
    return f"{self.module.name}_auto.h"

  @property
  def tag(self):
    return f"{self.module.name}_auto_h".upper()

  @property
  def stream(self):
    if self.__stream is None:
      self.__stream = _StreamFile(self.file_name + "~")
    return self.__stream

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #ifndef {self.tag}
      #define {self.tag}
    """.lstrip())

  def render_contents(self, stream):
    self.render_prologue(stream)
    entities = sorted(self.entities)
    for e in entities:
      for chunk in e._header_declarations:
        stream.write(chunk)
    for e in entities:
      for chunk in e._header_definitions:
        stream.write(chunk)
    self.render_epilogue(stream)

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #ifndef {self.tag}
      #define {self.tag}
    """.lstrip())

  def render_epilogue(self, stream):
    stream.write("\n#endif\n")


#
class Source(_EntityContainer, _SmartRenderer):
  
  complexity = 0
  __stream = None

  def __init__(self, module, index, *args, **kws):
    super().__init__(*args, **kws)
    self.module = module
    self.index = index

  @property
  def file_name(self):
    if self.module.source_count < 2:
      return f"{self.module.name}_auto.c"
    return f"{self.module.name}_auto{self.index}.c"

  @property
  def stream(self):
    if self.__stream is None:
      self.__stream = _StreamFile(self.file_name + "~")
    return self.__stream

  def add(self, entity):
    if entity not in self.entities:
      self.complexity += entity.complexity
    self.entities.add(entity)
    return self

  def render_contents(self, stream):
    self.render_prologue(stream)
    total_entities = set()
    for e in self.entities:
      total_entities.update(e.total_references)
    for e in sorted(total_entities):
      for chunk in e._source_declarations:
        stream.write(chunk)
    for e in sorted(self.entities):
      for chunk in e._source_definitions:
        stream.write(chunk)

  def render_prologue(self, stream):
    stream.write(f"""
      {_caption}
      #include "{self.module.header.file_name}"
    """.lstrip())


#
class Entity:
  
  __hdefs = None
  __sdefs = None
  __hdecls = None
  __sdecls = None
  __position = None
  __total_references = None
  __total_dependencies = None
  
  def __init__(self, *args, dependencies=(), references=(), **kws):
    super().__init__(*args, **kws)
    self.references = set()
    self.references.update(references)
    self.dependencies = _DependencySet(self)
    self.dependencies.update(dependencies)

  def __lt__(self, other):
    return self.position < other.position

  @property
  def total_references(self):
    if self.__total_references is None:
      self.__total_references = self.collect_references(set())
    return self.__total_references

  @property
  def total_dependencies(self):
    if self.__total_dependencies is None:
      self.__total_dependencies = self.collect_dependencies(set())
    return self.__total_dependencies

  def collect_references(self, entities):
    if self not in entities:
      entities.add(self)
      for ref in self.references:
        ref.collect_references(entities)
    return entities

  def collect_dependencies(self, entities):
    if self not in entities:
      entities.add(self)
      for dep in self.dependencies:
        # FIXME
        dep.collect_dependencies(entities)
    return entities

  @property
  def position(self):
    if self.__position is None:
      p = 0
      for d in self.total_dependencies:
        if d is not self:
          p = max(p, d.position)
      self.__position = p + 1
    return self.__position

  @property
  def complexity(self):
    return self._source_declarations.complexity + self._source_definitions.complexity

  def render_declarations(self, stream, header): pass
  
  def render_definitions(self, stream, header): pass

  @property
  def _header_declarations(self):
    if self.__hdecls is None:
      self.__hdecls = _Builder()
      self.render_declarations(self.__hdecls, True)
    return self.__hdecls

  @property
  def _header_definitions(self):
    if self.__hdefs is None:
      self.__hdefs = _Builder()
      self.render_definitions(self.__hdefs, True)
    return self.__hdefs
      
  @property
  def _source_declarations(self):
    if self.__sdecls is None:
      self.__sdecls = _Builder()
      self.render_declarations(self.__sdecls, False)
    return self.__sdecls

  @property
  def _source_definitions(self):
    if self.__sdefs is None:
      self.__sdefs = _Builder()
      self.render_definitions(self.__sdefs, False)
    return self.__sdefs


class _DependencySet(set):
  def __init__(self, entity, *args, **kws):
    super().__init__(*args, **kws)
    self.entity = entity

  def add(self, entity):
    self.entity.references.add(entity)
    super().add(entity)
    
  def update(self, *entities):
    self.entity.references.update(*entities)
    super().update(*entities)

#
class Code(Entity):
  def __init__(self, interface=None, implementation=None, definitions=None, *args, **kws):
    super().__init__(*args, **kws)
    self.__interface = interface
    self.__definitions = definitions
    self.__implementation = implementation

  def __repr__(self):
    return f"... <{self.__class__.__name__}>"

  def render_declarations(self, stream, header):
    if header:
      if self.__interface:
        stream.append(self.__interface)
    else:
      if self.__definitions:
        stream.append(self.__definitions)

  def render_definitions(self, stream, header):
    if not header:
      if self.__implementation:
        stream.append(self.__implementation)


#
class SystemHeader(Code):
  def __init__(self, header, *args, **kws):
    self.header_name = header
    super().__init__(interface=f"#include <{header}>\n", *args, **kws)

  def __repr__(self):
    return f"{self.header_name} <{self.__class__.__name__}>"