cmake_minimum_required(VERSION 3.15)

set(_site_candidates
  "${CMAKE_CURRENT_SOURCE_DIR}/${AUTOC_MODULE_NAME}.cmake.site"
  "${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.cmake.site"
)
foreach(_site IN LISTS _site_candidates)
  if(EXISTS "${_site}")
    include("${_site}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_site}")
    break()
  endif()
endforeach()

if(NOT DEFINED AUTOC)
  if(DEFINED AUTOC_MODULE_SOURCE AND EXISTS "${AUTOC_MODULE_SOURCE}")
    set(_autoc_default AUTO)
  elseif(DEFINED PROJECT_NAME AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.py")
    set(_autoc_default AUTO)
  else()
    set(_autoc_default OFF)
  endif()
  set(AUTOC ${_autoc_default} CACHE STRING "AutoC code generation mode: ON (unconditional), AUTO (incremental), OFF (disabled)")
endif()

if(AUTOC)
  find_package(Python 3.10 REQUIRED)
endif()

function(add_autoc_module module)
  set(args DIRECTORY MAIN_DEPENDENCY)
  set(listArgs COMMAND DEPENDS)
  cmake_parse_arguments(key "${flags}" "${args}" "${listArgs}" ${ARGN})
  if(NOT key_DIRECTORY)
    set(key_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
  endif()
  if(NOT key_MAIN_DEPENDENCY)
    set(key_MAIN_DEPENDENCY ${key_DIRECTORY}/${module}.py)
  endif()
  set(module_cmake ${key_DIRECTORY}/${module}.cmake)
  set(module_state ${key_DIRECTORY}/${module}.state)
  set(module_site ${key_DIRECTORY}/${module}.cmake.site)
  if(NOT EXISTS "${module_site}" AND EXISTS "${key_DIRECTORY}/${PROJECT_NAME}.cmake.site")
    set(module_site "${key_DIRECTORY}/${PROJECT_NAME}.cmake.site")
  endif()

  set(_generate OFF)

  if(AUTOC)
    if(NOT key_COMMAND)
      set(key_COMMAND ${Python_EXECUTABLE} ${key_MAIN_DEPENDENCY} ${module})
    endif()
    if(EXISTS ${key_MAIN_DEPENDENCY})
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${key_MAIN_DEPENDENCY} ${key_DEPENDS} ${module_cmake} ${module_state} ${module_site})
      if(AUTOC STREQUAL "AUTO")
        if(NOT EXISTS ${module_state} OR NOT EXISTS ${module_cmake})
          set(_generate ON)
        elseif(${key_MAIN_DEPENDENCY} IS_NEWER_THAN ${module_state})
          set(_generate ON)
        else()
          file(STRINGS ${module_state} _state_lines)
          foreach(_line IN LISTS _state_lines)
            string(REGEX MATCH "\\*([^\r\n]+)$" _match "${_line}")
            if(CMAKE_MATCH_1 AND NOT EXISTS "${key_DIRECTORY}/${CMAKE_MATCH_1}")
              set(_generate ON)
              break()
            endif()
          endforeach()
          if(NOT _generate)
            foreach(dep IN LISTS key_DEPENDS)
              if(dep IS_NEWER_THAN ${module_state})
                set(_generate ON)
                break()
              endif()
            endforeach()
          endif()
        endif()
      else()
        set(_generate ON)
      endif()
    elseif(NOT AUTOC STREQUAL "AUTO")
      message(FATAL_ERROR "AutoC: Generation script '${key_MAIN_DEPENDENCY}' not found for module '${module}'.")
    endif()
  endif()

  if(_generate)
    message(CHECK_START "Generating AutoC module " ${module})
    set(_env_cmd)
    if(AUTOC_PYTHONPATH)
      set(_env_cmd ${CMAKE_COMMAND} -E env "PYTHONPATH=${AUTOC_PYTHONPATH}")
    endif()
    execute_process(
      WORKING_DIRECTORY ${key_DIRECTORY}
      COMMAND ${_env_cmd} ${key_COMMAND}
      RESULT_VARIABLE gen_res
      OUTPUT_VARIABLE gen_out
      ERROR_VARIABLE gen_err
    )
    if(NOT gen_res EQUAL 0)
      message(CHECK_FAIL "failed")
      message(FATAL_ERROR "AutoC generator failed for '${module}':\n${gen_err}\n${gen_out}")
    else()
      message(CHECK_PASS "done")
      if(NOT EXISTS ${module_state} AND EXISTS ${module_cmake})
        file(TOUCH ${module_cmake})
      endif()
    endif()
  endif()

  if(NOT EXISTS ${module_cmake})
    message(FATAL_ERROR "AutoC: Pre-generated file '${module_cmake}' not found and AUTOC code generation is disabled.")
  endif()
  include(${module_cmake})

  if(AUTOC AND NOT AUTOC STREQUAL "AUTO")
    set(module_target ${module}-generate)
    set(_env_cmd)
    if(AUTOC_PYTHONPATH)
      set(_env_cmd ${CMAKE_COMMAND} -E env "PYTHONPATH=${AUTOC_PYTHONPATH}")
    endif()
    add_custom_target(${module_target}
      COMMAND ${_env_cmd} ${key_COMMAND}
      WORKING_DIRECTORY ${key_DIRECTORY}
    )
    if(TARGET ${module}-autoc)
      add_dependencies(${module}-autoc ${module_target})
    elseif(TARGET ${module}-auto)
      add_dependencies(${module}-auto ${module_target})
    endif()
  endif()
endfunction()
